services:
  app:
    build:
      context: ./.docker/app
      dockerfile: Dockerfile
    container_name: "${APP_NAME}"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "${APP_PORT}:80"
    networks:
      - yii2_docker_network

  mysql:
      image: mysql:8.0
      container_name: '${APP_NAME}_database'
      ports:
        - '${FORWARD_DB_PORT:-3301}:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - yii2_docker_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - '${PMA_PORT}:80'
    environment:
      - PMA_HOST:db
      - PMA_PORT:3300
      - PMA_USER:'${DB_USERNAME}'
      - PMA_PASSWORD='${DB_PASSWORD}'
      - UPLOAD_LIMIT=300M
      - MAX_EXECUTION_TIME=1200
    networks:
      - yii2_docker_network
    depends_on:
      - mysql

networks:
  yii2_docker_network:
    driver: bridge

volumes:
  mysql-data: